#!/bin/bash
#PBS -N CHAD
#PBS -l nodes=1:ppn=16
#PBS -l feature=16core
#PBS -l mem=20gb
#PBS -l walltime=1:00:00
## Put the output from jobs into the below directory
## Put both the stderr and stdout into a single file
#PBS -j oe
## Sepcify the working directory for this job

### You shouldn't need to change anything in this section ###
###                                                       ###
# Total Number of processors (cores) to be used by the job
HYAK_NPE=$(wc -l < $PBS_NODEFILE)
# Number of nodes used by MPICH
HYAK_NNODES=$(uniq $PBS_NODEFILE | wc -l )

### You shouldn't need to change anything in this section ###
###                                                       ###
echo "**** CPU and Node Utilization Information ****"
echo "This job will run on $HYAK_NPE total CPUs on $HYAK_NNODES different nodes"
echo ""
echo "Node:CPUs Used"
uniq -c $PBS_NODEFILE | awk '{print $2 ":" $1}'
echo "**********************************************"


module load gcc_4.4.7-ompi_1.6.5
module load anaconda2_4.2

cd $PBS_O_WORKDIR

mpiexec -n 16 python test2.py


### include any post processing here                      ###
###                                                       ###
#


exit 0
